In [15]:
pip install transformers

In [16]:
from transformers import pipeline

In [17]:
import transformers
print(transformers.__version__)

4.55.4


In [18]:
#Librosa is a Python package for audio and music analysis, right? Because we are doing speech to text, so we need this. So it provides various functions to quickly extract key audio features and metrics from the audio files
import librosa
import torch

import IPython.display as display

from transformers import Wav2Vec2ForCTC, Wav2Vec2Tokenizer

import numpy as np

In [19]:
#facebook
tokenizer= Wav2Vec2Tokenizer.from_pretrained("facebook/wav2vec2-base-960h")
model= Wav2Vec2ForCTC.from_pretrained("facebook/wav2vec2-base-960h")

The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'Wav2Vec2CTCTokenizer'. 
The class this function is called from is 'Wav2Vec2Tokenizer'.
Some weights of Wav2Vec2ForCTC were not initialized from the model checkpoint at facebook/wav2vec2-base-960h and are newly initialized: ['wav2vec2.masked_spec_embed']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [20]:
audio, sampling_rate = librosa.load("/content/audio.mp4a.wav" , sr=16000)

In [21]:
audio, sampling_rate

(array([-1.2604225e-05, -2.9764524e-05, -3.2835305e-05, ...,
         3.9124181e-03,  5.6634452e-03,  0.0000000e+00], dtype=float32),
 16000)

In [22]:
display.Audio("/content/audio.mp4a.wav", autoplay=True)


In [23]:
input_values = tokenizer(audio, return_tensors= 'pt').input_values
input_values

tensor([[-0.0010, -0.0011, -0.0011,  ...,  0.0202,  0.0297, -0.0009]])

In [24]:
#logits means non-normalized predictions
logits = model(input_values).logits
logits


tensor([[[ 14.7262, -25.6434, -25.3588,  ...,  -5.8097,  -7.7660,  -6.8947],
         [ 14.7000, -25.7121, -25.4288,  ...,  -5.8833,  -7.8501,  -6.9128],
         [ 14.6454, -25.6532, -25.3725,  ...,  -5.8273,  -7.8573,  -6.8667],
         ...,
         [ 13.9090, -25.7683, -25.5315,  ...,  -6.4320,  -8.6990,  -7.0684],
         [ 14.0063, -25.9133, -25.6693,  ...,  -6.4837,  -8.7361,  -6.9802],
         [ 13.9987, -26.1005, -25.8618,  ...,  -6.5783,  -8.7826,  -6.9709]]],
       grad_fn=<ViewBackward0>)

In [25]:
predicted_ids= torch.argmax(logits, dim = -1)

In [26]:
transcriptions = tokenizer.decode(predicted_ids[0])

In [34]:
transcriptions

"HELLO MY NAME IS MOMENT I'M DRAWN"

Some weights of Wav2Vec2ForCTC were not initialized from the model checkpoint at facebook/wav2vec2-base-960h and are newly initialized: ['wav2vec2.masked_spec_embed']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/tmp/ipython-input-2144572781.py:13: UserWarning: PySoundFile failed. Trying audioread instead.
  audio, sr = librosa.load("/content/audio.wav", sr=16000)


FileNotFoundError: [Errno 2] No such file or directory: '/content/audio.wav'